[package]
name = "ttt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
smallvec = "1"

skia-safe = { version = "*", features = ["gl", "textlayout"] }
gl = "*"
glutin = "*"
glutin-winit = "*"
winit = "*"
raw-window-handle = "0.5.0"

chumsky = "*"

ropey = "1"
